### ISSUE TITLE
Frontend index update script

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#136]
Some sort of script that can be run periodically to check in the image storage location to see if there are any new images that are currently not in the elastic index. If any are found, they will be indexed and then thumbnails will be generated for these images.

**Comment by ElevnLi** [comment]
[demo test.zip](https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/files/5648315/demo.test.zip)
I've wrapped up a version of frontend and backend working functionally, except for authentication which we decided to postpone after the quick demo on Monday. I'm trying to have some test of deepweeds, voc, cwfid data for the demo, but currently cwfid is working but deepweeds raise something like below:
![Screen Shot 2020-12-06 at 4 06 42 pm](https://user-images.githubusercontent.com/51065213/101272075-14ba8400-37dd-11eb-926c-30756500eebb.png)
Let me know if you can recognise this error. I attached the weedcoco file of the cwfid(working) and deepweeds(not working)
Also, the uploader turns out not that scalable to handle huge amount of images being uploaded, not because of the concurrency, but the rendering cost at frontend. I'll have a deep dive to see if it's manageable later. For now, it can handle uploads of several hundred images.

**Comment by jnothman** [comment]
The error means an annotation category name is not formatted correctly, but I'm not sure why this would be the case.

**Comment by jnothman** [comment]
Admittedly, that regex there is a bit of a hack; the transformation should be done elsewhere, in a way that is defensive enough to not crash the system if there's a single corrupted field. However, all it requires is that each category name has a colon (`:`) in it, and I can't see an example of that in `weedcoco/deepweeds_to_json/deepweeds_imageinfo.json`, nor reason for it in the importer for it...?

**Comment by jnothman** [comment]
Fixed with deposit logic.
