### ISSUE TITLE
User role and Dataset model

### ISSUE THREAD

**Issue by ElevnLi** [Sydney-Informatics-Hub/Weed-ID-Interchange#162]
I had a think about the user and dataset model. The user role includes basic django user model fields like name, email, password, is_superuser, is_staff and etc, so the extra fields I can think of is the latest upload to reference from the Dataset table and a list of accessible_datasets for future development when we want to enable user to download only certain datasets. Let me your thoughts. Thanks.
The design is as below:

```python
class Dataset(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, blank=False, null=False, unique=True)
    task_type = models.CharField(max_length=100, null=True)
    crop_type = models.CharField(max_length=100, null=True)
    weed_species = models.CharField(max_length=100, null=True)
    images_amount = models.IntegerField(null=True)
    citation = models.CharField(max_length=200, null=True)
    licence = models.CharField(max_length=100, null=True)

    upload_date = models.DateTimeField(blank=True, null=True)
    upload_user = models.ForeignKey('WeedidUser', on_delete=models.SET_NULL, blank=True, null=True)
    upload_status = models.TextChoices('None', 'Incomplete', 'Awaiting Review', 'Complete')
    upload_agcontext = JSONField(null=True)
    upload_annotation_type = models.CharField(max_length=100, default='WeedCOCO')


class WeedidUser(AbstractUser):
    latest_upload = models.ForeignKey(Dataset, on_delete=models.SET_NULL, blank=True, null=True)
    accessible_datasets = models.ManyToManyField(Dataset, blank=True)
```

**Comment by jnothman** [comment]
The stuff related to crop type, task type, etc, won't necessarily be able to be stored in 100 chars, and I don't see the point of constraining ourselves to a fixed schema. Certainly not for weed species, where there will be multiple species for many datasets. We'll probably want multiple image counts, e.g. per species or per agcontext. For these reasons I think it might be best to store dataset info as a JSON blob, whether in postgres or ES. (I read a blog the other day that pointed to the merits of using Postgres as a nosql database using [these dox functions](https://github.com/robconery/dox), allowing it to be extended into a relational schema when needed.)

I'd put the upload data in there, but everything else I'd put in a JSON blob.

**Comment by ElevnLi** [comment]
```python
class Dataset(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, blank=False, null=False, unique=True)
    images_amount = models.IntegerField(null=True)

    upload_date = models.DateTimeField(blank=True, null=True)
    upload_user = models.ForeignKey('WeedidUser', on_delete=models.SET_NULL, blank=True, null=True)
    upload_status = models.TextChoices('None', 'Incomplete', 'Awaiting Review', 'Complete')
    upload_agcontext = JSONField(null=True)
    upload_annotation_type = models.CharField(max_length=100, default='WeedCOCO')


class WeedidUser(AbstractUser):
    latest_upload = models.ForeignKey(Dataset, on_delete=models.SET_NULL, blank=True, null=True)
    accessible_datasets = models.ManyToManyField(Dataset, blank=True)
```
The field `upload_agcontext` is in json format. May I know what to be expected from the agconext and metadata form? I'm not sure about which field is essential for each upload, and the content rendered in frontend is definitely expecting some data following certain protocol, not something without any constraint.

**Comment by jnothman** [comment]
Let's step back a bit. A dataset ideally includes:
* publication metadata in accordance with schema.org/DataSet, which treats a dataset as a creative work with citable authorship, institutional affiliation, sponsorship, year of publication, funding information, DOI, etc. We had defined weedcoco such that a single JSON file could contain multiple datasets. For this reason we defined `collections` (and `collection_memberships`; see https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/blob/master/weedcoco/spec_overview.md). From a relational database perspective, we might design that each Annotation to have a Collection (now called "dataset") as a foreign key. I now think this is excessive complexity for a first implementation, and we should just put metadata into the `info` section of the uploaded/downloaded COCO file.
* one or more agcontexts, which define the collection parameters for the images within that dataset. Each image is associated with one agcontext. We allowed a single dataset to have multiple agcontexts, because we wanted to support researchers / data collectors putting together a bunch of images collected and annotated similarly, but in different crops/locations/times as a single, citable dataset. The change of crop, location or season would necessitate a different agcontext.
* images
* annotations, which define applicable ML tasks
* (not yet implemented: train/test split)

All of this information (except for the image data) is stored in the weedcoco, and hence need not be explicitly stored in the database. However, it would be helpful to store a summary for the purposes of rapid access (parsing a full weedcoco may be prohibitive with lots of annotations), indexing for search, and aggregation. Such a summary has _too much_ structure to store in a simple relational table as you initially proposed above, and – like the index records we are using for images – too little predefined structure that would justify writing out a relational schema and managing its migration as your understanding of what needs to be accommodated in that schema changes. This is precisely the case where NoSQL databases are valuable. If there is a consistent way of producing these summaries then it is the [validity](https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/blob/master/weedcoco/validation.py) of the input, and the processing of that input to produce a summary, which ensures that it follows a protocol expected by the frontend.

**Comment by ElevnLi** [comment]
Do you have a specific nosql db server to use, like the basic key-value pairs (redis, which has been created to play the message queue role for celery), document-based like MongoDB or Graph DB? MongoDB should be the best for this case right?

**Comment by ElevnLi** [comment]
The reason I wanted to avoid MongoDB was that I haven't had psql and mongo server co-exist within Django, as [handling multiple db](https://docs.djangoproject.com/en/3.1/topics/db/multi-db/) includes things like migration is pretty painful, which increases the complexity and uncertainty. If storing metadata and agcontext as JSONField in psql can work, it would be more efficient for development under time pressure. If not, I can have a look how to make it work, maybe connecting to MongoDB separately and use things like pymongo.

**Comment by jnothman** [comment]
You can use postgres as a nosql server, with a jsonfield (and indexing if needed), or elasticsearch. Happy to discuss tomorrow.

**Comment by ElevnLi** [comment]
https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/#jsonfield
"PostgreSQL has two native JSON based data types: json and jsonb. The main difference between them is how they are stored and how they can be queried. PostgreSQL’s json field is stored as the original string representation of the JSON and must be decoded on the fly when queried based on keys. The jsonb field is stored based on the actual structure of the JSON which allows indexing. The trade-off is a small additional cost on writing to the jsonb field. JSONField uses jsonb."
I think JSONField should be all good to use.

**Comment by jnothman** [comment]
Since it's mostly for display, while the authoritative data is stored in the on-disk repository, I don't think it matters!

**Comment by jnothman** [comment]
Done in ?#156
